# Docker compose configuration for project
# Tool that allows us to run our docker image easily from project location.
# Helps us manage different services (eg: API, database)

version: "3"

# Service called app, build with context current directory
services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8001:8001" # Map host port 8001 to port 8001 in docker image
    volumes: # Get updates from local machine to docker container in real-time. No need to restart docker
      - ./app:/app # Maps our project's app directory to docker image's app directory
    # Run our docker image in development mode and allow us to connect to it on port 8001
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

# export UID=${UID} && export GID=${GID}