# Generated by Django 2.1.15 on 2020-08-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quit',
            new_name='quiz',
        ),
    ]
