# Generated by Django 2.1.15 on 2020-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200814_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
